### ISSUE TITLE
Operations dashboard [Teach Nagaland]

### ISSUE THREAD

**Issue by salilsamanvay** [avniproject/Teach-Nagaland#9]

**Comment by adamsanadi6** [comment]
Link to Dashboard: http://52.66.206.164/superset/dashboard/63/

**Comment by salilsamanvay** [comment]
@sachsk admin user count has to be checked again as it is not correct as of now.

**Comment by salilsamanvay** [comment]
Admin user is still reflecting as zero whereas we have one admin user

**Comment by adamsanadi6** [comment]
Admin Users Count issue has been fixed.

**Comment by vaijayanthisundaram** [comment]
- Total users : usage of “join” vs “left join”  in query “total users in the system”
- Teachers with address : “join” used for just teacher count ( do we not count teachers with no addresses).
- Similarly for users and observations query, inner join used for address
- Seems like “Userwise Observation Count with pass/fail” and “Userwise Observation Count w/o pass fail” are the same.
- “Duplicate teacher” -unsure abt query logic. Needs rechecking.
- “Teacher With Completed Observation” - chart in explore mode shows errors.
- “District Level Users” - does this mean  they do not have school and block ? If so, then logic is correct.

**Comment by vaijayanthisundaram** [comment]
After discussing with Sachin, only the following points need to be checked for this dashboard:

- Seems like “Userwise Observation Count with pass/fail” and “Userwise Observation Count w/o pass fail” are the same.
“Teacher With Completed Observation” - chart in explore mode shows errors.

**Comment by adamsanadi6** [comment]
I have already discussed the issue 'Userwise Observation Count with pass/fail' and 'Userwise Observation Count without pass/fail' being same with Salil. It's the same in the AP dashboard as well. He mentioned that he would discuss it with the client and provide further information.

I have already discussed this issue with Sachin. The error in 'Teacher With Completed Observation' is occurring because we are directly displaying the entire dataset. It's challenging to select all 209 columns(This is very time consuming. Also there is no shortcut to select all the column at once).
